### PR TITLE
Remove PHY management assumptions. Expose SMI. Narrow scope.

### PR DESCRIPTION
**Pull request by mitchmindtree**
*@thalesfragoso feel free to take or leave this! This direction for
`stm32-eth` has been motivated by my use of the crate over the past few
months for this installation. We currently use a branch that combines a
variation on these changes along with the `stm32f1` branch (#23).*

This PR introduces a couple of significant breaking changes, primarily:

1. **Remove the assumption that the MCU must be associated with a single
   PHY.** MCUs are capable of Ethernet communication without requiring
   knowledge of the PHYs involved at all. In cases where a MCU is
   connected directly to a switch IC via MII or RMII (e.g. using
   something like the KSZ8863), association with a single PHY does not
   make meaningful sense, and an API that expects one can be a little
   frustrating to work around.
2. **Refactor the `smi` module and expose the `Smi` type.** The idea
   behind this change is to narrow the scope of `stm32-eth` to the
   fundamentals of enabling Ethernet communication, while exposing the
   necessary components to allow PHY management to be handled externally
   (e.g. via [`mdio`](https://crates.io/crates/mdio) or device-specific
   crate like [`ksz8863`](https://crates.io/crates/ksz8863)).
   Further, by not requiring that the `Eth` constructor take ownership
   over the `MDIO` and `MDC` pins, we allow the user to use them for
   custom MDIO-based protocols. E.g. the KSZ8863 requires setting the
   R/W OP code bits to `0b00`, however this is not possible to configure
   using the STM32 MAC's limited SMI interface (`MACMIIAR`), so a
   bit-banged implementation of MDIO is required. Without these changes,
   it is not possible to use `stm32-eth` alongside a custom bit-banged
   implementation on the MDIO and MDC pins.

Here's roughly how usage of the new SMI API should look:

```rust
// Borrows MACMIIAR and MACMIIDR from `Eth` along with the MDIO and MDC pins.
let mut smi = eth.smi(&mut mdc, &mut mdio);

// Do stuff with `smi` in scope.
let data = smi.read(phy_addr, reg_addr);
smi.write(phy_addr, reg_addr, data);

// `Smi` instance is dropped at end of scope and borrows are released.
```

Some uses might be as simple as:

```rust
let data = eth.smi(&mut mdc, &mut mdio).read(phy_addr, reg_addr);
```

The `pktgen.rs` example has been updated to demonstrate.

**Follow-up**

- Update `stm32f1` PR for removal of MDIO and MDC pin ownership.

### CODE REVIEW

**Comment by systec-ms** [comment]
I would go along with that. I checked out the repo from @mitchmindtree and rebased https://github.com/stm32-rs/stm32-eth/pull/33 onto it. And tested with the PHY KSZ8081RNA and STM32F767, the whole thing ran flawless.

**Comment by datdenkikniet** [comment]
Is this PR still relevant? AFAICT most of (if not all) of the changes requested have already been merged.

@mitchmindtree @systec-ms @franeklubi

**Comment by mitchmindtree** [comment]
@datdenkikniet I haven't been following the recent sweep of merges (though happy to see it happen!) but if this work has been merged under other PRs I'm happy for this to be closed. Would be nice if, in closing, we could link to the PR or commit where this work has already landed.

**Comment by datdenkikniet** [comment]
Thanks for the swift reply! I'm not entirely sure where/if all changes have ended up where they should. tried to rebase the changes myself, but there has been quite a bit of reshuffling since this PR was last updated so I couldn't quite figure it out. 

Let's wait and see what the others say :)

**Comment by systec-ms** [comment]
This PR was fully merged with https://github.com/stm32-rs/stm32-eth/pull/34.
Also, https://github.com/stm32-rs/stm32-eth/issues/8 can be closed in my opinion.

**Pull request closed without merging**
