### PR TITLE
Fill in device capabilities

### PR DESCRIPTION
**Pull request by birkenfeld**
Obviously not to be merged as-is, especially the second commit, more as a FYI.

### CODE REVIEW

**Comment by astro** [comment]
These changes are partially obsoleted by #9. Update needed.

**Comment by birkenfeld** [comment]
OK, updated this. The important note from the commit:

> I'm not sure about the checksumming, but not setting the
> max_transmission_unit will leave it at zero and this
> isn't handled in smoltcp -- as far as I can tell.

**Comment by thalesfragoso** [comment]
Right now we don't do any checksums in hardware, I was a bit confused about the `ChecksumCapabilities` behavior, but whitequark clarified to me that `Both` (the default) means that the stack should calculate all the checksums, so we don't need to change that right now. I'm planning to play with checksum offload in the future, but probably not right now.

With respect to the MTU, that change is already on master. So I guess we can close this PR, what do you think ?

**Comment by birkenfeld** [comment]
Oh, I made this PR from the master branch and this was overridden. But no matter, since this should have been closed anyway :)

**Pull request merged**
